#ifndef SAITAMA_ATOMIC_H
#define SAITAMA_ATOMIC_H

#define WGPU_TARGET_MACOS			1
#define WGPU_TARGET_LINUX_X11		2
#define WGPU_TARGET_WINDOWS			3
#define WGPU_TARGET_LINUX_WAYLAND	4
#define WGPU_TARGET_IOS				5
#define WGPU_TARGET_ANDROID			6

#define WGPU_DESKTOP (WGPU_TARGET != WGPU_TARGET_ANDROID && WGPU_TARGET != WGPU_TARGET_IOS)

#endif